#!/bin/bash
if [ "$1" == "coverage" ] ; then
  source .venv/bin/acivate
  DATABASE_URL="sqlite:///test.db" coverage run -m pytest && coverage html && rm coverage.svg && coverage-badge -o coverage.svg
  exit 0
elif [ "$1" == "tests" ]; then
  source .venv/bin/activate
  DATABASE_URL="sqlite:///test.db" python -m pytest -s -x
  exit 0
else
    if [ "$1" != "" ]; then
      echo -e "\033[1;31mComando Inválido\033[0m: $0\033[1;32m $@ \033[0m"
    fi
    echo Comandos disponíveis:
    echo -e "\033[1;32m coverage\033[0m:\t\tRoda o teste de cobertura e gera o html e svg de coverage" 
    echo -e "\033[1;32m tests\033[0m:\t\t\tExecuta os testes via pytest até a primeira falha" 
    exit 1
fi